hw-k8s-operators
otus-kuber-2020-04/funkypenguin18_platform pull request #11
Opened 2020-06-14 15:59 UTC by funkypenguin18

# Выполнено ДЗ №7

 - [+] Основное ДЗ
 - [+] Задание с 🐍 

## В процессе сделано:
- Создан и применен CustomResourceDefinition для mysql оператора в манифесте deploy/crd.yaml
- Создан и применен  CustomResource для mysql оператора в манифесте deploy/cr.yaml
- Собиран и добавлен в репозиторий Docker образ.
- Развернуты mysql при помощи оператора+джобы.
- Добавлены тестовые данные в БД.
- Проверено, выполнились ли backup и restore jobs.

2020-06-14 17:18 UTC, Jasstkn requested changes
Добрый вечер! По основному домашнему заданию все в порядке, но не увидела у вас ридми (или описания в PR как проверить дз, что было сделано) и описания выполнения заданий со звездочками :( Опишите их выполнение также в ридми или в описание PR.
Также не увидела у вас ответ на вопрос со слайда 22, поэтому возвращаю на доработку.

2020-06-15 07:17 UTC, funkypenguin18 commented
> Добрый вечер! По основному домашнему заданию все в порядке, но не увидела у вас ридми (или описания в PR как проверить дз, что было сделано) и описания выполнения заданий со звездочками :( Опишите их выполнение также в ридми или в описание PR.
> Также не увидела у вас ответ на вопрос со слайда 22, поэтому возвращаю на доработку.

Классика - коммит сделал из подкаталога и не добавил ридми =)
fixed.

2020-06-16 07:04 UTC, Jasstkn approved these changes

2020-06-16 07:04 UTC, Jasstkn commented on README.md
> +
Все верно, используется кеширование.

2020-06-16 07:04 UTC, merged